services:

  # =========================
  # Admin App
  # =========================
  wekode.adreag.admin:
    image: ${IMAGE_ADMIN}
    build:
      context: ./AdminApp
      dockerfile: AdminApp/Dockerfile
      args:
       - UID=${UID}
       - GID=${GID}
       - DOT_NET_BUILD_CONFIG=Release
    container_name: wekode.adreag.admin
    restart: unless-stopped
    user: ${UID}:${GID}
    ports:
      - "${PORT_ADMIN}:8080"
    env_file:
      - .env
    #environment:
    #  - LDAPTLS_CACERT=/certs/ad-ca.crt
    #  - LDAPTLS_REQCERT=demand
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      # - ./certs/ad-ca.crt:/certs/ad-ca.crt:ro
    # no external IAM dependency; uses Active Directory instead
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "20m"
        max-file: "3"

  # =========================
  # Registration App
  # =========================
  wekode.adreag:
    image: ${IMAGE_REGISTER}
    build:
      context: ./RegistrationApp
    container_name: wekode.adreag
    restart: unless-stopped
    ports:
      - "${PORT_REGISTER}:8080"
    env_file:
      - .env
    #environment:
    #  - LDAPTLS_CACERT=/certs/ad-ca.crt
    #  - LDAPTLS_REQCERT=demand
    volumes:
      - ./data:/data
      - /etc/localtime:/etc/localtime:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      # - ./certs/ad-ca.crt:/certs/ad-ca.crt:ro
    # no external IAM dependency; uses Active Directory instead
    networks:
      - internal
    logging:
      driver: "json-file"
      options:
        mode: "non-blocking"
        max-size: "20m"
        max-file: "3"

# =========================
# =========================
# Networks
# =========================
networks:
  internal:
    driver: bridge